title: Poo/java
description: Ajuda iniciais a programação orientada a objetos
template:
  repo: poojava-template
  name: poojava
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
